[Inductor][FX passes] Pre grad pass modified graph should be topological sorted (#103794)
Error from 14k github models.
Minimized repro: please check the unit test I added
Error:
```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Argument 'getitem_2' of Node 'sin' was used before it has been defined! Please check that Nodes in the graph are topologically ordered
graph():
    %l_x_ : torch.Tensor [#users=1] = placeholder[target=L_x_]
    %sin : [#users=1] = call_function[target=torch.sin](args = (%getitem_2,), kwargs = {})
    %unbind : [#users=2] = call_function[target=torch.unbind](args = (%l_x_,), kwargs = {dim: 0})
    %getitem_2 : [#users=1] = call_function[target=operator.getitem](args = (%unbind, 0), kwargs = {})
    %getitem_3 : [#users=1] = call_function[target=operator.getitem](args = (%unbind, 1), kwargs = {})
    %sin_1 : [#users=1] = call_function[target=torch.sin](args = (%getitem_3,), kwargs = {})
    %stack : [#users=1] = call_function[target=torch.stack](args = ([%sin, %sin_1],), kwargs = {})
    return (stack,)
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/103794
Approved by: https://github.com/devashishshankar