Revert "change pre_autograd to pre_dispatch tracing (#101818)"
This reverts commit d944dcc6a189aa7ba2485b3c8e7630e27a678d25.

Reverted https://github.com/pytorch/pytorch/pull/101818 on behalf of https://github.com/izaitsevfb due to Breaks internal builds see D46629736 TypeError: wrap_key() got an unexpected keyword argument pre_autograd ([comment](https://github.com/pytorch/pytorch/pull/101818#issuecomment-1587837667))