ROCm triton commit pin update (#114348)
Small bump in rocm triton commit pin to resolve reported issue on 7900XTX
> RuntimeError: Triton Error [HIP]: Code: 719, Messsage: unspecified launch failure
https://github.com/ROCmSoftwarePlatform/triton/issues/396

Pull Request resolved: https://github.com/pytorch/pytorch/pull/114348
Approved by: https://github.com/jeffdaily