Revert "Adding entry-point based support for out-of-tree rendezvous plugins (#132633)"
This reverts commit e1c813bbcf7d6c433a744f83d6f05b8bbe00aca9.

Reverted https://github.com/pytorch/pytorch/pull/132633 on behalf of https://github.com/ZainRizvi due to Sorry but this is causing internal tests to fail with the error `ImportError: cannot import name '_register_out_of_tree_handlers' from 'torch.distributed.elastic.rendezvous.registry'` ([comment](https://github.com/pytorch/pytorch/pull/132633#issuecomment-2315716201))