fix missing nvml in c10/cuda/driver_api.cpp issue (#112121)
Since https://github.com/pytorch/pytorch/pull/99699 introduced a dependency on nvml for oom reporting in `c10/cuda/driver_api.h`, `c10/cuda/driver_api.cpp`, and `reportProcessMemoryInfo` from `c10/cuda/CUDACachingAllocator.cpp`, we've seen failures regarding cuda expandable segments and oom reporting in NVIDIA's internal CI, specifically on Jetson devices which don't have nvml support as it is incompatible with Jetson. Example failures using the latest upstream on Orin AGX node:

`python test/test_cuda.py -k test_notifies_oom` generates

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/pytorch/pytorch/test/test_cuda.py", line 1643, in _worker
    results[t] = torch.nn.functional.conv2d(results[t], weight, padding=0)
RuntimeError: CUDA driver error: out of memory
```

`python test/test_cuda_expandable_segments.py` generates

```
Traceback (most recent call last):
  File "/opt/pytorch/pytorch/test/test_cuda_expandable_segments.py", line 12, in <module>
    exec(compile(open(filepath).read(), filepath, mode='exec'))
  File "/opt/pytorch/pytorch/test/test_cuda.py", line 66, in <module>
    class TestCuda(TestCase):
  File "/opt/pytorch/pytorch/test/test_cuda.py", line 1609, in TestCuda
    @unittest.skipIf(not TEST_CUDNN, 'CUDNN not available')
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 4628, in wrapped
    self._value = self._cb()
  File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_cuda.py", line 20, in <lambda>
    TEST_CUDNN = LazyVal(lambda: TEST_CUDA and torch.backends.cudnn.is_acceptable(torch.tensor(1., device=CUDA_DEVICE)))
RuntimeError: handle_0 INTERNAL ASSERT FAILED at "/opt/pytorch/pytorch/c10/cuda/driver_api.cpp":15, please report a bug to PyTorch.
```

This PR intends to fix this issue by adding various dlopen checks to make sure nvml actually exists, and safely fall back to using the older libcuda based features of cuda expandable segments and oom reporting if nvml is not found.

Pull Request resolved: https://github.com/pytorch/pytorch/pull/112121
Approved by: https://github.com/eqy, https://github.com/ngimel, https://github.com/albanD