Add missing load_template function to utils.py
The cherry-picked commit depends on load_template() which exists in main
but not in v2.8.0 branch. This function is used by mm_common.py to load
Jinja2 kernel templates.

Also added Path import from pathlib to support the function.

Fixes ImportError: cannot import name 'load_template' from 'torch._inductor.utils'