Build fails due to unused exception parameter error
Summary:
fbsource//xplat/air/integrations/ssg:ml_runtime has a dependency on fbsource//xplat/caffe2:pt_defs.bzl. It shows consistent "-Wunused-exception-parameter" errors  given removed the unused "e"  from the catch block.  Therefore, removed the unused "e"  

  Failing tests
  https://www.internalfb.com/intern/test/844425183629975
  https://www.internalfb.com/intern/test/844425183629994
  https://www.internalfb.com/intern/test/844425184247702

  Stderr:
  xplat/caffe2/aten/src/ATen/native/TensorAdvancedIndexingUtils.h:80:28: error: unused exception parameter 'e' [-Werror,-Wunused-exception-parameter]
   80 |   } catch (std::exception& e) {
      |                            ^
  1 error generated.

Test Plan: Unit tests

Differential Revision: D84890985